# toml-docs-start lang-main
[en]
languageName = "English"
contentDir = "content/en"
weight = 1
title = "Polish Annoyance Filters"
# toml-docs-end lang-main
# toml-docs-start lang-param
[en.params.head]
tagline = "Filters that hide and block pop-ups, widgets, newsletters, push notifications, arrows and other irritating elements on Polish websites (include Polish GDPR-Cookies Filters)."
[en.params.social]
title = "Follow us"
caption = ""
[en.params.footer]
license = "Licensed under Creative Commons (<a href='https://creativecommons.org/licenses/by-sa/4.0/' class='link-secondary' target='_blank' rel='noopener noreferrer'>CC BY-SA 4.0</a>)."
# toml-docs-end lang-param
[en.params.sections.blog]
reference = "More Posts"
[en.params.sections.projects]
reference = "More Projects"

[pl]
languageName = "Polski"
contentDir = "content/pl"
weight = 0
# toml-docs-end lang-main
# toml-docs-start lang-param
[pl.params.head]
tagline = "Filtry ukrywające i blokujące wyskakujące okienka, widgety, newslettery, powiadomienia push, strzałki i inne drażniące elementy (Polskie Filtry RODO-Ciasteczkowe są już w nich zawarte)."
[pl.params.social]
title = "Śledź nas"
caption = ""
[pl.params.footer]
license = "Licencja <a href='https://creativecommons.org/licenses/by-sa/4.0/' class='link-secondary' target='_blank' rel='noopener noreferrer'>CC BY-SA 4.0</a>."
# toml-docs-end lang-param
[pl.params.sections.blog]
reference = "Więcej postów"
[pl.params.sections.projects]
reference = "Więcej projektów"
