title: Polskie Filtry Elementów Irytujących
description: Filtry ukrywające i blokujące wyskakujące okienka, widgety, newslettery, powiadomienia push, strzałki i inne drażniące elementy.
theme: jekyll-theme-architect
lang: pl-PL
include: [_redirects]
github:
    owner_url: https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters
sass:
  style: compressed
compress_html:
  clippings: all
  comments:  ["<!-- ", " -->"]
  endings:   all
google_site_verification: fNut01rhp845fu903ZfwVGKe-vWAz-IecDu7MHZ0bLw
