title: Polskie filtry elementów irytujących
description: Filtry ukrywające i blokujące wyskakujące okienka, widgety, newslettery, powiadomienia push, strzałki i inne drażniące elementy.
theme: jekyll-theme-architect
lang: pl-PL
github:
    owner_url: https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters
sass:
  sass_dir: _sass
  style: compressed
compress_html:
  clippings: all
  comments:  ["<!-- ", " -->"]
  endings:   all
