
title: Polskie Filtry Elementów Irytujących
theme: hugo-architect-theme
pygmentsCodeFences: true
pygmentsUseClasses: true
DefaultContentLanguage: pl
enableEmoji: true
baseURL: https://polishannoyancefilters.netlify.app/
disablePathToLower: true

params:
  use_sass: true
  show_downloads: false
  description: Filtry ukrywające i blokujące wyskakujące okienka, widgety, newslettery, powiadomienia push, strzałki i inne drażniące elementy (Polskie Filtry RODO-Ciasteczkowe są już w nich zawarte).
  gh_repo_owner: FiltersHeroes
  gh_repo_name: PolishAnnoyanceFilters
  google_site_verification: fNut01rhp845fu903ZfwVGKe-vWAz-IecDu7MHZ0bLw
  footer_text: 'Paczka ikon systemów operacyjnych i kategorii została stworzona przez [Icons8](https://icons8.com). Czcionka Architects Daughter jest na licencji [SIL OFL](/fonts/SIL_OFL.txt).'
  author: Filters Heroes

languages:
  en:
    title: Polish Annoyance Filters
    contentDir: content/en
    params:
      description: Filters that hide and block pop-ups, widgets, newsletters, push notifications, arrows and other irritating elements on Polish websites (include Polish GDPR-Cookies Filters).
      footer_text: 'The package of operating systems and category icons was created by [Icons8](https://icons8.com). Architects Daughter font has [SIL OFL](/fonts/SIL_OFL.txt) license.'
    weight: 2
    languageName: English
  pl:
    weight: 1
    languageName: Polski
    contentDir: content/pl
