[build]
  command = "hugo --minify"

[build.environment]
  HUGO_VERSION = "0.124.0"
  GO_VERSION = "1.22.x"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL"

[[redirects]]
  from = "https://polishannoyancefilters.netlify.app/otherfiltersforadblockers/"
  to = "https://majkiit.github.io/polish-ads-filter/"
  status = 301
  force = true

[[redirects]]
  from = "/cookieconsentoldsyntax"
  to = "/PolishCookieConsent/old-syntax"
  status = 301

[[redirects]]
  from = "/cookieconsentsyntax"
  to = "/PolishCookieConsent/syntax"
  status = 301

[[redirects]]
  from = "/cookieconsentissues"
  to = "https://www.reddit.com/r/PolishCookieConsent/"
  status = 301

[[redirects]]
  from = "/PolishCookieConsent/issues"
  to = "https://www.reddit.com/r/PolishCookieConsent/"
  status = 301
  force = true

# [[plugins]]
#     package = "@gethinode/netlify-plugin-dartsass"

[[plugins]]
    package = "netlify-plugin-hugo-cache-resources"
	[plugins.inputs]
	# Relative path to source directory in case you use Hugo's "--s" option
	# srcdir = ""
