[build]
  command = "gulp sass && hugo --minify"

[build.environment]
  HUGO_VERSION = "0.48"

[[redirects]]
  from = "http://polishannoyancefilters.netlify.com/*"
  to = "https://polishannoyancefilters.netlify.com/:splat"
  status = 301
  force = true

[context.deploy-preview]
  command = "gulp sass && hugo -b $DEPLOY_PRIME_URL"
