[build]
  command = "hugo --minify"

[build.environment]
  HUGO_VERSION = "0.82.0"

[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL"

[[redirects]]
  from = "https://polishannoyancefilters.netlify.app/otherfiltersforadblockers/"
  to = "https://majkiit.github.io/polish-ads-filter/"
  status = 301
  force = true
