[build]
  command = "hugo --minify"

[build.environment]
  HUGO_VERSION = "0.56.1"

[[redirects]]
  from = "http://polishannoyancefilters.netlify.com/*"
  to = "https://polishannoyancefilters.netlify.com/:splat"
  status = 301
  force = true

[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL"
