[[main]]
  name = "Główna"
  pageRef = "/"
  weight = 1

[[main]]
  name = "Zgłoszenia"
  pageRef = "/issues"
  weight = 2

[[main]]
  name = "Moduły"
  pageRef = "/modules"
  weight = 3

# [[main]]
#   name = "Hosts"
#   pageRef = "#hosts"
#   weight = 4

# [[main]]
#   name = "Kontakt"
#   pageRef = "/contact"
#   weight = 10

# [[main]]
#   name = "Blog"
#   pageRef = "#blog"
#   weight = 6

# [[main]]
#   name = "Tagi"
#   pageRef = "/tags/"
#   weight = 40

[[social]]
  name = "GitHub"
  pre = "fab fa-github"
  url = "https://github.com/FiltersHeroes/PolishAnnoyanceFilters"
  weight = 20

[[social]]
  name = "RSS"
  pre = "fas fa-rss"
  url = "/index.xml"
  weight = 30
